[workspace]
exclude = [
  "crates/rapid-cli/src/templates/server",
  "crates/rapid-cli/src/templates/remix",
  "examples/fullstackRemix",
  "examples/server",
  "examples/fullstackNextjs"
]
members = ["crates/*"]
