[package]
name = "rapid-cli"
version = "0.0.1"
edition = "2021"
description = "The CLI tool for the Rapid framework"
homepage = "https://cincinnati.ventures"
license = "MIT"
keywords = ["CLI", "web-framework", "rapid"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
