name: Storybook

on: [push, pull_request] # Stoybook will be deployed on every push and pull request

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/rapid-ui
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 19.x
        uses: actions/setup-node@v1
        with:
          node-version: 19.x

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=storybook-static --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 3160fdc6-812b-403f-a540-9a1a6b2b0524
