name: Deploy (ui-landing)

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: 🚀 Deploy
        runs-on: ubuntu-latest
        steps:
            - name: ⬇️ Checkout repo
              uses: actions/checkout@v3
              with:
                  persist-credentials: true

            - name: 👀 Read app name
              uses: SebRollen/toml-action@v1.0.2
              id: app_name
              with:
                  file: './docs/ui-landing/fly.toml'
                  field: 'app'

            - name: 🚀 Deploy Production
              if: ${{ github.ref == 'refs/heads/main' }}
              uses: superfly/flyctl-actions@1.3
              with:
                  args: 'deploy --remote-only --config ./docs/ui-landing/fly.toml --dockerfile ./docs/ui-landing/Dockerfile --build-arg COMMIT_SHA=${{ github.sha }}'
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
