name: Deploy (landing)

on:
    push:
        branches:
            - test

jobs:
    deploy:
        name: 🚀 Deploy
        runs-on: ubuntu-latest
        steps:
            - name: ⬇️ Checkout repo
              uses: actions/checkout@v3

            - name: 👀 Read app name
              uses: SebRollen/toml-action@v1.0.2
              id: app_name
              with:
                  file: 'fly.toml'
                  field: 'app'

            - name: 🚀 Deploy Production
              if: ${{ github.ref == 'refs/heads/main' }}
              uses: superfly/flyctl-actions@1.3
              with:
                  args: 'deploy --build-arg COMMIT_SHA=${{ github.sha }}'
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
