name: Publish @rapid-web/react to npm


on:
  push:
    tags:
      - 'rapid-react-[0-9]+.[0-9]+.[0-9]+' # We only want to publish when a tag is pushed

jobs:
  build-react:
    name: Deploy @rapid-web/react
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/rapid-react
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '19.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies and build 🔧
        run: pnpm install --no-frozen-lockfile && pnpm run build
      - name: Publish package on NPM 📦
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
