name: Publish @rapid/ui to npm

on:
  push:
    tags:
      - 'rapid-ui-[0-9]+.[0-9]+.[0-9]+' # We only want to publish when a tag is pushed
jobs:
  build-ui:
    name: Deploy @rapid/ui
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/rapid-ui
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '19.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: npm ci
      - name: Build package via Vite
        run: npm run build
      - name: Publish package on NPM 📦
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
